### ISSUE TITLE
ETQ ifremer je souhaiterais savoir comment amender le package

### ISSUE THREAD

**Issue by ALanguillaume** [mariemorfin/inser#1]
## Validation

À la fin de la session d'accompagnement 

- [x] Je comprends la structure du package
- [x] Je sais faire passer le devtools::check()
- [x] Je sais faire un commit
- [x] Je sais travailler dans une branche
- [x] Je sais faire une Pull Request

### Livrables 

- [x] J'ai une checklist  de comment faire : https://github.com/mariemorfin/inser/wiki/Aide-m%C3%A9moire-pour-amender-le-package
- [x] J'ai un lien vers l'enregistrement vidéo de le session (lien envoyé par mail)

**Comment by mariemorfin** [comment]
OK pour moi
